describe('E-Commerce excercise Test', function() {
    it('Doing an order', function(){

        cy.visit('https://automationexercise.com')
        cy.get("a[href='/login']").click()
        cy.get('[data-qa="login-email"]').type('kevindemo25@yopmail.com')
        cy.get('[data-qa="login-password"]').type('Automatizacion25')
        cy.get('[data-qa="login-button"]').click()

        cy.get('.shop-menu > .nav > :nth-child(2) > a').click()
        cy.get(':nth-child(2) > .panel-heading > .panel-title > a > .badge').click()
        cy.get('#Men > .panel-body > ul > :nth-child(1) > a').click()
        cy.get(':nth-child(6) > .product-image-wrapper > .choose > .nav > li > a').click()
        cy.get('[name="quantity"]').clear().type('2')
        cy.get(':nth-child(5) > .btn').click()
        cy.get('.modal-footer > .btn').click()
        cy.get(':nth-child(2) > .panel-heading > .panel-title > a > .badge').click()
        cy.get('#Men > .panel-body > ul > :nth-child(2) > a').click()
        cy.get('.active').contains('Jeans')
        cy.get(':nth-child(3) > .product-image-wrapper > .choose > .nav > li > a').click()
        cy.get('[name="quantity"]').clear().type('2')
        cy.get(':nth-child(5) > .btn').click()
        cy.get('.modal-footer > .btn').click()
        cy.get('.shop-menu > .nav > :nth-child(3)').click()
        cy.get('.col-sm-6 > .btn').click()
        cy.get(':nth-child(7) > .btn').click()
        cy.get('[data-qa="name-on-card"]').type('Kevin QA')
        cy.get('[data-qa="card-number"]').type('123456789')
        cy.get('[data-qa="cvc"]').type('123')
        cy.get('[data-qa="expiry-month"]').type('01')
        cy.get('[data-qa="expiry-year"]').type('31')
        cy.get('[data-qa="pay-button"]').click()
        cy.get('[data-qa="continue-button"]').click()
        cy.get('.shop-menu > .nav > :nth-child(4) > a').click()
    })
})